// The cities the unit names its time zones by, in its own order, and the time each keeps.
//
// The cities and their order between the ends of the list are not all confirmed against a unit.
// Each city keeps one offset from UTC in every year, with no summer time.

/** Each city the [Time Zone] dialog lists, with how far its time stands ahead of UTC, in minutes. */
const ZONES: readonly (readonly [string, number])[] = [
  ["Abu Dhabi", 240],
  ["Adelaide", 570],
  ["Alaska", -540],
  ["Almaty", 300],
  ["Amman", 180],
  ["Amsterdam", 60],
  ["Arizona", -420],
  ["Astana", 300],
  ["Asuncion", -180],
  ["Athens", 120],
  ["Atlantic Time (Canada)", -240],
  ["Auckland", 720],
  ["Azores", -60],
  ["Baghdad", 180],
  ["Baja California", -480],
  ["Baku", 240],
  ["Bangkok", 420],
  ["Beijing", 480],
  ["Beirut", 120],
  ["Belgrade", 60],
  ["Berlin", 60],
  ["Bern", 60],
  ["Bogota", -300],
  ["Brasilia", -180],
  ["Bratislava", 60],
  ["Brisbane", 600],
  ["Brussels", 60],
  ["Bucharest", 120],
  ["Budapest", 60],
  ["Buenos Aires", -180],
  ["Cairo", 120],
  ["Canberra", 600],
  ["Cape Verde Is.", -60],
  ["Caracas", -240],
  ["Casablanca", 60],
  ["Cayenne", -180],
  ["Central America", -360],
  ["Central Time (US & Canada)", -360],
  ["Chennai", 330],
  ["Chihuahua", -360],
  ["Chongqing", 480],
  ["Coordinated Universal Time", 0],
  ["Copenhagen", 60],
  ["Darwin", 570],
  ["Dhaka", 360],
  ["Dublin", 0],
  ["Eastern Time (US & Canada)", -300],
  ["Edinburgh", 0],
  ["Ekaterinburg", 300],
  ["Fiji", 720],
  ["Georgetown", -240],
  ["Greenland", -120],
  ["Guadalajara", -360],
  ["Guam", 600],
  ["Hanoi", 420],
  ["Harare", 120],
  ["Hawaii", -600],
  ["Helsinki", 120],
  ["Hobart", 600],
  ["Hong Kong", 480],
  ["Indiana (East)", -300],
  ["International Date Line West", -720],
  ["Irkutsk", 480],
  ["Islamabad", 300],
  ["Istanbul", 180],
  ["Jakarta", 420],
  ["Jerusalem", 120],
  ["Kabul", 270],
  ["Karachi", 300],
  ["Kathmandu", 345],
  ["Kolkata", 330],
  ["Krasnoyarsk", 420],
  ["Kuala Lumpur", 480],
  ["Kuwait", 180],
  ["Kyiv", 120],
  ["La Paz (Mexico)", -420],
  ["La Paz (Bolivia)", -240],
  ["Lima", -300],
  ["Lisbon", 0],
  ["Ljubljana", 60],
  ["London", 0],
  ["Madrid", 60],
  ["Magadan", 660],
  ["Manaus", -240],
  ["Marshall Is.", 720],
  ["Mazatlan", -420],
  ["Melbourne", 600],
  ["Mexico City", -360],
  ["Mid-Atlantic", -120],
  ["Midway Island", -660],
  ["Minsk", 180],
  ["Monrovia", 0],
  ["Monterrey", -360],
  ["Montevideo", -180],
  ["Moscow", 180],
  ["Mountain Time (US & Canada)", -420],
  ["Mumbai", 330],
  ["Muscat", 240],
  ["Nairobi", 180],
  ["New Caledonia", 660],
  ["New Delhi", 330],
  ["Newfoundland", -210],
  ["Novosibirsk", 420],
  ["Nuku'alofa", 780],
  ["Osaka", 540],
  ["Pacific Time (US & Canada)", -480],
  ["Paris", 60],
  ["Perth", 480],
  ["Petropavlovsk-Kamchatsky", 720],
  ["Port Louis", 240],
  ["Port Moresby", 600],
  ["Prague", 60],
  ["Pretoria", 120],
  ["Quito", -300],
  ["Reykjavik", 0],
  ["Riga", 120],
  ["Riyadh", 180],
  ["Rome", 60],
  ["Samoa", 780],
  ["San Juan", -240],
  ["Santiago", -240],
  ["Sapporo", 540],
  ["Sarajevo", 60],
  ["Saskatchewan", -360],
  ["Seoul", 540],
  ["Singapore", 480],
  ["Skopje", 60],
  ["Sofia", 120],
  ["Solomon Is.", 660],
  ["Sri Jayawardenepura", 330],
  ["St. Petersburg", 180],
  ["Stockholm", 60],
  ["Sydney", 600],
  ["Taipei", 480],
  ["Tallinn", 120],
  ["Tashkent", 300],
  ["Tbilisi", 240],
  ["Tehran", 210],
  ["Tijuana", -480],
  ["Tokyo", 540],
  ["Ulaan Bataar", 480],
  ["Urumqi", 480],
  ["Vienna", 60],
  ["Vilnius", 120],
  ["Vladivostok", 600],
  ["Volgograd", 180],
  ["Warsaw", 60],
  ["Wellington", 720],
  ["West Central Africa", 60],
  ["Windhoek", 120],
  ["Yakutsk", 540],
  ["Yangon (Rangoon)", 390],
  ["Yerevan", 240],
  ["Zagreb", 60],
];

/** The cities, in the order the dialog lists them. */
export const TIME_ZONE_CITIES: readonly string[] = ZONES.map(([city]) => city);

const ZONE_OF = new Map(ZONES);

/** The city a unit as it ships is set to. */
export const TIME_ZONE_SHIPPED = "Tokyo";

/**
 * How far `city`'s time stands ahead of UTC, in milliseconds, the same in every year. A name the
 * list does not hold is read as the city the unit ships with.
 */
export function zoneOffsetMs(city: string): number {
  return (ZONE_OF.get(city) ?? ZONE_OF.get(TIME_ZONE_SHIPPED) ?? 0) * 60_000;
}
